version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    groups:
      php-dependencies:
        update-types:
        - "minor"
        - "patch"
    allow:
      - dependency-type: direct
    versioning-strategy: increase-if-necessary

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    groups:
      js-dependencies:
        update-types:
        - "minor"
        - "patch"
    allow:
      - dependency-type: direct
    versioning-strategy: increase-if-necessary
